In [1]:
import numpy as np

In [3]:
a = np.array([[2,3,6]])


In [4]:
b = np.array([[2],[3],[4]])

multiplication of vectors

In [5]:
a * b

array([[ 4,  6, 12],
       [ 6,  9, 18],
       [ 8, 12, 24]])

multiplication vectors by a skalar

In [6]:
a * 8

array([[16, 24, 48]])

In [7]:
s = 2.0
a = [2,3,4]
b = np.array([[2,3,4]])

In [14]:
#a * s
#Error

In [9]:
b * s

array([[4., 6., 8.]])

### Translating vectors

[1,1] + [10,20]\
[2,2] + [10,20]\
[3,3] + [10,20]

In [10]:
a = np.array([[1,2,3]]).T
b = np.array([[10,20]])
a + b

array([[11, 21],
       [12, 22],
       [13, 23]])

In [11]:
a = np.array([[1,2,3]])
b = np.array([[10,20]]).T
a + b

array([[11, 12, 13],
       [21, 22, 23]])

In [12]:
b

array([[10],
       [20]])

### Vectors modul

In [24]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [22]:
len(a)

4

In [23]:
np.linalg.norm(a)

5.477225575051661

### Dot Product of vectors

In [26]:
v = np.array([[1,2,3,5]])
w = np.array([[2],[3],[1],[4]])
np.dot(v,w)

array([[31]])

In [32]:
s = 1
np.dot(s * v,w)

array([[31]])

### Hadamarovo multiplication 

In [4]:
a = np.array([5, 4, 8, 2]) 
b = np.array([1, 0,.5,1]) 
a*b

array([5., 0., 4., 2.])